# Generated by Django 2.2.6 on 2019-11-01 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neigh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField(verbose_name='ObjectID')),
                ('name', models.CharField(max_length=50, verbose_name='Neighborhood Name')),
                ('area', models.FloatField(verbose_name='Shape Area')),
                ('length', models.FloatField(verbose_name='Shape Length')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
